services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: open_telemetry_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./Otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./Otel/logs:/etc/output:rw # Store the logs (not commited in git)
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver
  prometheus:
      image: bitnami/prometheus
      container_name: prometheus
      volumes:
        - ./Otel/prometheus.yaml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
  grafana:
      image: grafana/grafana
      container_name: grafana
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - ./Otel/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml
      ports:
        - 3000:3000
  zipkin:
      container_name: zipkin-traces
      image: openzipkin/zipkin:latest
      ports:
        - "9411:9411"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"

  